### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by denkravts** [hldh214/buff2steam#12]
can u help me?

I do not understand how I can solve this
![image](https://user-images.githubusercontent.com/88428534/128151536-7d6a04f7-7c23-41de-b4a7-357b0a724aff.png)

**Comment by hldh214** [comment]
Please make sure your `config.json` is a **valid** json.

**Comment by denkravts** [comment]
still don't understand
what do i need to do with the config file? i tried to use Notepad ++ and plugins but nothing works

**Comment by denkravts** [comment]
Okay, it seems like xD works
thanks for saying what's the problem
Still, is it possible to take a price from auto-purchase steam?

**Comment by hldh214** [comment]
Currently `auto-purchase` is not implemented.
