### ISSUE TITLE
Code not working properly

### ISSUE THREAD

**Issue by weixiao030** [hldh214/buff2steam#14]
Sorry to bother you, I really can't figure out what's wrong
![QQ图片20220905032629](https://user-images.githubusercontent.com/84442419/188330342-bdd41773-e66d-4497-860a-2aa1b28d33f9.png)

**Comment by hldh214** [comment]
打断点看看这个 response.text 是啥

**Comment by weixiao030** [comment]
![image](https://user-images.githubusercontent.com/84442419/188339608-8772c7b2-7ae2-4415-bdc7-f5d9dfa4d16d.png)

**Comment by weixiao030** [comment]
![image](https://user-images.githubusercontent.com/84442419/188339654-a1715c8a-8249-4cc0-a360-2a746dc831c9.png)

**Comment by weixiao030** [comment]
> 打断点看看这个回复。文字是啥

什么意思

**Comment by weixiao030** [comment]
> 打断点看看这个回复。文字是啥

![image](https://user-images.githubusercontent.com/84442419/188340126-39eaa1bb-cb01-4df6-9719-a924e4a10407.png)

**Comment by hldh214** [comment]
是不是没把 cookie 填进来
https://github.com/hldh214/buff2steam/blob/ng/.github/README-zh-CN.md#%E8%8E%B7%E5%8F%96-buff-session

**Comment by weixiao030** [comment]
> 没把cookie填入不是 https://github.com/hldh214/buff2steam/blob/ng/.github/README-zh-CN.md#%E8%8E%B7%E5%8F%96-buff-session

写了，这应该没有问题吧
![image](https://user-images.githubusercontent.com/84442419/188340313-a55eba30-8a49-40cb-9374-27d7dee2e733.png)
