### ISSUE TITLE
Is there anyway to use BUFF163 api 

### ISSUE THREAD

**Issue by tktq40** [hldh214/buff2steam#16]
Hi In your py code, you use  'https://buff.163.com/market/goods?goods_id=' to get price n stuff, I just found out that there's other way like using 'https://buff.163.com/api/market/goods?game=csgo' but unfortunately I have no document about this API, is there any possible way to use it?

**Comment by hldh214** [comment]
After all, this is not a so-called public API, so it's not expected to have any related documentation. The code in this repository was developed based on requests from their PC website.

**Comment by tktq40** [comment]
I just found out a way to use their API, it seems like it returns the same way with pc but more informative in JSON, eg : 
"https://buff.163.com/api/market/goods?game=csgo&page_num=${page}&page_size=80&&sort_by=price.desc"
just change the page from 1 to the latest, hope it helps

**Comment by hldh214** [comment]
I thought it's already here?
https://github.com/hldh214/buff2steam/blob/a8413f2d7da80f5e11ee4c324607906c00da6f05/buff2steam/provider/buff.py#L66-L72

**Comment by tktq40** [comment]
my bad for being misinformation, thank you for pointing it out.
