### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by tameco68** [hldh214/buff2steam#18]
I don't know anything about python and need installation help...

**Comment by marshudi** [comment]
No problem! I can help you with the installation of Python.

Here's a step-by-step guide for installing Python on different platforms:

**Windows:**
1. Visit the official Python website at https://www.python.org/downloads/.
2. Scroll down to the "Download" section and click on the "Windows" button.
3. On the next page, you'll see two options: Python 3.x.x and Python 2.x.x. It's recommended to choose Python 3 as it is the latest version.
4. Click on the "Download Python 3.x.x" button to download the Python installer.
5. Once the installer is downloaded, double-click on it to run.
6. On the first page of the installer, make sure to check the box that says "Add Python 3.x to PATH."
7. Proceed with the installation by following the prompts. You can leave the default settings as they are.
8. Once the installation is complete, open the command prompt by searching for "cmd" in the Start menu.
9. In the command prompt, type `python` and press Enter. If Python is successfully installed, you should see the Python version and a prompt `>>>`.

**macOS:**
1. Visit the official Python website at https://www.python.org/downloads/.
2. Scroll down to the "Download" section and click on the "macOS" button.
3. On the next page, you'll see two options: Python 3.x.x and Python 2.x.x. It's recommended to choose Python 3 as it is the latest version.
4. Click on the "Download Python 3.x.x" button to download the Python installer.
5. Once the installer is downloaded, double-click on it to run.
6. Follow the prompts in the installer, and on the "Installation Type" page, make sure to select "Install for all users" and "Add Python 3.x to PATH."
7. Proceed with the installation by clicking "Install" and entering your administrator password if prompted.
8. Once the installation is complete, open the Terminal application.
9. In the Terminal, type `python` and press Enter. If Python is successfully installed, you should see the Python version and a prompt `>>>`.

**Linux:**
1. Open a terminal.
2. Check if Python is already installed by typing `python3 --version`. If you see the Python version, it means Python is already installed.
3. If Python is not installed, you can install it using the package manager specific to your Linux distribution. For example, on Ubuntu or Debian, you can use the following command:
   ```
   sudo apt-get update
   sudo apt-get install python3
   ```
4. Once the installation is complete, type `python3` in the terminal and press Enter. If Python is successfully installed, you should see the Python version and a prompt `>>>`.

After installing Python, you can run Python programs by creating and saving a `.py` file with the Python code and running it using the command `python filename.py` in the command prompt or terminal.

I hope this helps you get started with Python! If you have any further questions, feel free to ask.

**Comment by d0nker420** [comment]
> No problem! I can help you with the installation of Python.
> 
> 
> 
> Here's a step-by-step guide for installing Python on different platforms:
> 
> 
> 
> **Windows:**
> 
> 1. Visit the official Python website at https://www.python.org/downloads/.
> 
> 2. Scroll down to the "Download" section and click on the "Windows" button.
> 
> 3. On the next page, you'll see two options: Python 3.x.x and Python 2.x.x. It's recommended to choose Python 3 as it is the latest version.
> 
> 4. Click on the "Download Python 3.x.x" button to download the Python installer.
> 
> 5. Once the installer is downloaded, double-click on it to run.
> 
> 6. On the first page of the installer, make sure to check the box that says "Add Python 3.x to PATH."
> 
> 7. Proceed with the installation by following the prompts. You can leave the default settings as they are.
> 
> 8. Once the installation is complete, open the command prompt by searching for "cmd" in the Start menu.
> 
> 9. In the command prompt, type `python` and press Enter. If Python is successfully installed, you should see the Python version and a prompt `>>>`.
> 
> 
> 
> **macOS:**
> 
> 1. Visit the official Python website at https://www.python.org/downloads/.
> 
> 2. Scroll down to the "Download" section and click on the "macOS" button.
> 
> 3. On the next page, you'll see two options: Python 3.x.x and Python 2.x.x. It's recommended to choose Python 3 as it is the latest version.
> 
> 4. Click on the "Download Python 3.x.x" button to download the Python installer.
> 
> 5. Once the installer is downloaded, double-click on it to run.
> 
> 6. Follow the prompts in the installer, and on the "Installation Type" page, make sure to select "Install for all users" and "Add Python 3.x to PATH."
> 
> 7. Proceed with the installation by clicking "Install" and entering your administrator password if prompted.
> 
> 8. Once the installation is complete, open the Terminal application.
> 
> 9. In the Terminal, type `python` and press Enter. If Python is successfully installed, you should see the Python version and a prompt `>>>`.
> 
> 
> 
> **Linux:**
> 
> 1. Open a terminal.
> 
> 2. Check if Python is already installed by typing `python3 --version`. If you see the Python version, it means Python is already installed.
> 
> 3. If Python is not installed, you can install it using the package manager specific to your Linux distribution. For example, on Ubuntu or Debian, you can use the following command:
> 
>    ```
> 
>    sudo apt-get update
> 
>    sudo apt-get install python3
> 
>    ```
> 
> 4. Once the installation is complete, type `python3` in the terminal and press Enter. If Python is successfully installed, you should see the Python version and a prompt `>>>`.
> 
> 
> 
> After installing Python, you can run Python programs by creating and saving a `.py` file with the Python code and running it using the command `python filename.py` in the command prompt or terminal.
> 
> 
> 
> I hope this helps you get started with Python! If you have any further questions, feel free to ask.

Nice job gpt-chan
