### ISSUE TITLE
Error and suggest

### ISSUE THREAD

**Issue by yroovtc1** [hldh214/buff2steam#28]
Keep getting this error after a while. Can you add an option to resume at a selected page to avoid wasting time running from the beginning?

Traceback (most recent call last):
  File "buff2steam\__main__.py", line 85, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "buff2steam\__main__.py", line 79, in main
  File "buff2steam\__main__.py", line 14, in main_loop
  File "buff2steam\provider\buff.py", line 68, in get_items
  File "buff2steam\provider\buff.py", line 55, in request
buff2steam.exceptions.BuffError: {'error': '访问频率过高, 请稍后重试……', 'code': 'System Error'}
[14428] Failed to execute script '__main__' due to unhandled exception!

And can you add a feature like sort by quantity, to compare the high quantity item first?
![image](https://github.com/hldh214/buff2steam/assets/97154479/37be4cdc-6501-472e-b9cb-1bc43b6b1cf1)

**Comment by volodymyrzuyev** [comment]
The error you are getting is related to the buff API rate limit. You should increase the `request_interval` value in `buff` portion of `config.json`. Alternatively, you can set up a `try catch` in the `__main__.py` file. 

As far as I know buff API does not provide a way to sort goods by quantity, or other metrics, so it would probably be difficult to implement your proposed feature

**Comment by hldh214** [comment]
> As far as I know buff API does not provide a way to sort goods by quantity, or other metrics, so it would probably be difficult to implement your proposed feature

The API does indeed support such parameters, as we are utilizing the same API as their website. Therefore, our scripts can perform the same functions as their website.

For years, I believed this project was dead, but it's surprising to see everyone's enthusiasm. Perhaps I should consider recommitting my energy to this project.
