### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by MixFix228** [hldh214/buff2steam#29]
Good afternoon
Can you tell me why nothing is displayed in the interface?
![image](https://github.com/hldh214/buff2steam/assets/53259363/3639fb4f-dab8-49b3-8b25-f60949deb794)

**Comment by MixFix228** [comment]
What are the correct settings in the config to get results?

**Comment by volodymyrzuyev** [comment]
If no items show up in the cli, no items will show up in the GUI
