### ISSUE TITLE
CSGO support

### ISSUE THREAD

**Issue by hldh214** [hldh214/buff2steam#4]

**Comment by kevin-vista** [comment]
请问未来会加入对CSGO的支持吗？

**Comment by hldh214** [comment]
> 请问未来会加入对CSGO的支持吗？

会的. 这段时间比较忙, 也欢迎大家出谋划策.

**Comment by zren45** [comment]
希望可以加入 bitskin 和buff的比价~~

**Comment by hldh214** [comment]
> 希望可以加入 bitskin 和buff的比价~~

其他饰品网站我也有想过加上作为对比参考, 比如:
https://github.com/hldh214/buff2steam/blob/master/buff2steam/c5.py
这个就是之前写的 c5 的比价

但是还没想好怎么去整合进现在的逻辑中
因为现在是先去查 buff 的价格, 然后去查 steam 社区市场的价格来获得对应比例
按照之前 (master 分支) 的实现, c5 的查询也是需要先查 buff 获得可能低价的饰品之后再去 c5 查是否有更低的买入价
这样就比较狭隘, 因为这样就用不上 c5 这边查询出来的可能低价的饰品, 只能依赖 buff 那边的查询结果来对应查 c5

若想加入 bitskin 则也可能有同样的问题.
不知道大家有啥想法没有~
