### ISSUE TITLE
CSRF verification failed in Buff auto-buy module

### ISSUE THREAD

**Issue by Harrypotterrrr** [hldh214/buff2steam#5]
Hi, I ran your code, debug and check the process of auto-buy items on buff. Requests return the text says: `CSRF verification failed`. After I appended headers with csrf-token, it works out.
Finding out your code without any header information including csrf-token and other misc, I wonder how your code manages to buy correctly, If it is for the sake of the security to remove headers and cookie in your config file, or there are any workarounds to deal with this post in a simple way?
I am a freshman in spider and WEB technology, so I appreciate your reply in advance! 😊

**Comment by hldh214** [comment]
https://github.com/hldh214/buff2steam/blob/af1b5370bb7a0cdc08cae093427df2bf1bd88542/buff2steam/buff.py#L22-L27

Actually there is such things inside `buff.py`.

如有疑问, 欢迎追问

**Comment by Harrypotterrrr** [comment]
> https://github.com/hldh214/buff2steam/blob/af1b5370bb7a0cdc08cae093427df2bf1bd88542/buff2steam/buff.py#L22-L27
> 
> Actually there is such things inside `buff.py`.
> 
> 如有疑问, 欢迎追问

Oh, thanks for your instant reply! It is my fault to skip over this part of your code and mistake self.post for requests.post 😂 One question left. I found there are some other information in HEADER, as listed below,
``` json
headers = {
                   "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36",
                   "Accept": "application/json, text/javascript, */*; q=0.01",
                   "Accept-Encoding": "gzip, deflate, br",
                   "Accept-Language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
                   "Connection": "keep-alive",
                   "Content-Length": "150",
                   "Cpmtemt-Type": "application/json",
                   "X-CSRFToken": "xxxxxxxxxxxxxxxx",
                   "X-Requested-With": "XMLHttpRequest",
                   "Host": "buff.163.com",
                   "Origin": "https://buff.163.com",
                   "Referer": "https://buff.163.com/market/goods?goods_id = 14704&from=market"
               }
```
I notice you only fill header with `csrf` and `Referer`, so I wonder if buff-server only checks these two  attributes (in other words, this server inspects request not strict enough), or `X-CSRFToken` and `Referer` are enough to meet any post requests.

**Comment by hldh214** [comment]
> I wonder if buff-server only checks these two attributes

So far, yes.
And there are also other HTTP headers used for anti-spider such as:
 - Cookie
 - User-Agent

 > `X-CSRFToken` and `Referer` are enough to meet any post requests

In a short word, not enough.

In Python, the HTTP client (we use `requests`) will automatically add required headers for a single request.
You can verify it by `print(opener.headers)`:
```python
import requests

opener = requests.session()
opener.headers['whatever_you_want'] = 'lalaland'
opener.headers['Referer'] = 'https://example.com'

print(opener.headers)
# {'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'whatever_you_want': 'lalaland', 'Referer': 'https://example.com'}
```

You can visit [MDN](https://developer.mozilla.org/docs/Web/HTTP/Headers) for HTTP headers specific infos.

**Comment by Harrypotterrrr** [comment]
Oh, I get it. thanks for your patience and long reply. Your website is very useful for me! 😄
